import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '简介',
    },
    {
      type: 'doc',
      id: 'core-concepts',
      label: '核心概念',
    },
    {
      type: 'doc',
      id: 'common-spec',
      label: '通用规范',
    },
    {
      type: 'category',
      label: '处理管道',
      link: {
        type: 'doc',
        id: 'pipeline/README',
      },
      items: [
        {
          type: 'doc',
          id: 'pipeline/selector',
          label: 'selector - CSS选择器',
        },
        {
          type: 'doc',
          id: 'pipeline/jsonpath',
          label: 'jsonpath - JSON查询',
        },
        {
          type: 'doc',
          id: 'pipeline/regex',
          label: 'regex - 正则表达式',
        },
        {
          type: 'doc',
          id: 'pipeline/string',
          label: 'string - 字符串操作',
        },
        {
          type: 'doc',
          id: 'pipeline/cache',
          label: '缓存操作',
        },
      ],
    },
    {
      type: 'category',
      label: '媒体类型规范',
      items: [
        {
          type: 'autogenerated',
          dirName: 'media-types',
        },
      ],
    },
    {
      type: 'category',
      label: 'Schema 定义',
      items: [
        {
          type: 'autogenerated',
          dirName: 'schema',
        },
      ],
    },
    {
      type: 'category',
      label: '示例',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: '高级主题',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        },
      ],
    },
    {
      type: 'doc',
      id: 'disclaimer',
      label: '⚠️ 免责声明',
    },
  ],
};

export default sidebars;
